-- | Auto-generated module containing code snippets
-- | Generated by scripts/extract-snippets.js
-- | DO NOT EDIT THIS FILE MANUALLY
module CodeSnippets where

import Prelude

-- | Snippet metadata
type SnippetInfo =
  { name :: String
  , content :: String
  , source :: String
  , lines :: String
  }

-- ** Snippet Content Constants **

snippet_selectionMClass_content :: String
snippet_selectionMClass_content = "class (Monad m) <= SelectionM selection m where\n  appendTo        :: selection -> Element -> Array (SelectionAttribute) -> m selection\n\n  selectUnder     :: selection -> Selector selection -> m selection\n\n  attach          :: Selector selection -> m selection\n\n  filterSelection :: selection -> Selector selection -> m selection\n\n  mergeSelections :: selection -> selection -> m selection\n\n  setAttributes   :: selection -> Array (SelectionAttribute) -> m Unit\n\n  on              :: selection -> Behavior selection -> m Unit\n\n  openSelection   :: selection -> Selector selection -> m selection\n\n  simpleJoin      :: ∀ datum.  selection -> Element -> (Array datum) -> (Datum_ -> Index_) -> m selection\n\n  nestedJoin      :: ∀ f datum. Foldable f =>\n                     selection -> Element -> (Datum_ -> f datum) -> (Datum_ -> Index_) -> m selection\n\n  updateJoin      :: ∀ datum.  selection -> Element -> (Array datum) -> (Datum_ -> Index_)\n    -> m { enter :: selection, exit :: selection, update :: selection }"

snippet_simulationM2Class_content :: String
snippet_simulationM2Class_content = "class (Monad m, SimulationM selection m) <= SimulationM2 selection m | m -> selection where\n  -- ** Dynamic Updates **\n\n  update :: forall d. SimulationUpdate d -> m { nodes :: Array (D3_SimulationNode d), links :: Array D3Link_Swizzled }\n\n  -- ** Animation (Tick Functions) **\n\n  addTickFunction    :: Label -> Step selection -> m Unit\n\n  removeTickFunction :: Label                   -> m Unit"

-- | All available snippets
snippets :: Array SnippetInfo
snippets =
  [ { name: "selectionMClass"
    , content: snippet_selectionMClass_content
    , source: "src/lib/PSD3/Capabilities/Selection.purs"
    , lines: "85-258"
    }
  , { name: "simulationM2Class"
    , content: snippet_simulationM2Class_content
    , source: "src/lib/PSD3/Capabilities/Simulation.purs"
    , lines: "254-320"
    }
  ]

-- | Look up a snippet by name
getSnippet :: String -> String
getSnippet name = case name of
  "selectionMClass" -> snippet_selectionMClass_content
  "simulationM2Class" -> snippet_simulationM2Class_content
  _ -> "Snippet not found: " <> name

-- | Get snippet info by name
getSnippetInfo :: String -> SnippetInfo
getSnippetInfo name = case name of
  "selectionMClass" ->
    { name: "selectionMClass"
    , content: snippet_selectionMClass_content
    , source: "src/lib/PSD3/Capabilities/Selection.purs"
    , lines: "85-258"
    }
  "simulationM2Class" ->
    { name: "simulationM2Class"
    , content: snippet_simulationM2Class_content
    , source: "src/lib/PSD3/Capabilities/Simulation.purs"
    , lines: "254-320"
    }
  _ ->
    { name: "not-found"
    , content: "Snippet not found: " <> name
    , source: ""
    , lines: ""
    }
